version: '3.8'

services:
  application:
    build: .
    image: fitness-prediction:latest
    container_name: fitness-prediction
    ports:
      - "8080:8080"
    volumes:
      - ./airflow:/app/airflow
